### PR TITLE
Implement various Windows build fixes

### LINKED ISSUE #12: win compilation errors
I'm working on a DMX plugin for vcv rack using your awesome library. It's working great on macOS but I'm getting some build problems on win64 build via my actions build on GitHub. I'm using https://github.com/VCVRack/rack-plugin-toolchain to build and they use a common pattern where both the windows and linux builds are done in an ubuntu docker container. My first issue is files are case sensitive on linux so the inclusion of :

```
#include <WinSock2.h> breaks as the file needs to be for both
#include <winsock2.h>
#include <basetsd.h>
```

2nd I'm hitting this cascade of errors:

```
src/clients/e131.c: In function 'e131_unicast_dest':
src/clients/e131.c:81:24: error: storage size of 'hints' isn't known
   81 |   struct addrinfo *ai, hints;
      |                        ^~~~~
src/clients/e131.c:84:7: warning: implicit declaration of function 'getaddrinfo' [-Wimplicit-function-declaration]
   84 |   if (getaddrinfo(host, NULL, &hints, &ai) != 0) {
      |       ^~~~~~~~~~~
src/clients/e131.c:91:45: error: invalid use of undefined type 'struct addrinfo'
   91 |   dest->sin_addr = ((struct sockaddr_in *)ai->ai_addr)->sin_addr;
      |                                             ^~
src/clients/e131.c:95:3: warning: implicit declaration of function 'freeaddrinfo' [-Wimplicit-function-declaration]
   95 |   freeaddrinfo(ai);
```

On win64 build it can't calculate the sizeof hints. Any thoughts on how to proceed?

// get the address info of the host (the results are a linked list)
  struct addrinfo *ai, hints;
  memset(&hints, 0, sizeof hints);

### PR DESCRIPTION
**Pull request by braewoods**
This also closes #12.

### CODE REVIEW

**Comment by hhromic** [comment]
Hi @braewoods , thanks for the contribution and helping on the Windows front! 💯 

Your changes looks good but I have the following two questions:
* For `setsockopt`, according to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/functions/setsockopt.html) and [Windows](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-setsockopt) the fourth argument should be qualified with `const`.  Therefore, can you update your changes for `(const void *)` instead? Thanks for spotting this one!
* Can you elaborate on why you need to switch the `PRIu32` format to `lu`? I just tested a simple program in MSYS2 (which I also use) and it works fine for the output of `ntohl`. The `PRIu32` format macro is supposed to be portable.

**Comment by braewoods** [comment]
>     * For `setsockopt`, according to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/functions/setsockopt.html) and [Windows](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-setsockopt) the fourth argument should be qualified with `const`.  Therefore, can you update your changes for `(const void *)` instead? Thanks for spotting this one!
>     * The same above applies to `sendto` as well for the second argument.
Fair, but I didn't think it would matter in practice because non-const variables will get silently promoted to const in such contexts.

>     * Can you elaborate on why you need to switch the `PRIu32` format to `lu`? I just tested a simple program in MSYS2 (which I also use) and it works fine for the output of `ntohl`. The `PRIu32` format macro is supposed to be portable.
I was getting compiler warnings on the UCRT64 toolchain because ntohl returns an unsigned long, where as PRIu32 resolves to a printf specifier for unsigned int. In practice this should not matter for Windows because long and int are the same size even on 64 bit Windows, but this is the ABI Microsoft decided on, and I have no idea why GCC is even warning for it.

**Comment by braewoods** [comment]
First set of changes done.

**Comment by braewoods** [comment]
Here's the errors I was getting without my changes:
```src/e131.c: In function 'e131_pkt_dump':
src/e131.c:316:19: error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'u_long' {aka 'long unsigned int'} [-Werror=format=]
  316 |   fprintf(stream, "  Layer Vector ........... %" PRIu32 "\n", ntohl(packet->root.vector));
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                               |
      |                                                               u_long {aka long unsigned int}
In file included from src/e131.c:26:
C:/msys64/ucrt64/include/inttypes.h:101:17: note: format string is defined here
  101 | #define PRIu32 "u"
src/e131.c:327:19: error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'u_long' {aka 'long unsigned int'} [-Werror=format=]
  327 |   fprintf(stream, "  Layer Vector ........... %" PRIu32 "\n", ntohl(packet->frame.vector));
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                               |
      |                                                               u_long {aka long unsigned int}
C:/msys64/ucrt64/include/inttypes.h:101:17: note: format string is defined here
  101 | #define PRIu32 "u"```

**Comment by hhromic** [comment]
> Fair, but I didn't think it would matter in practice because non-const variables will get silently promoted to const in such contexts.

Yep, I'm aware that promotion takes place, but I prefer code to be as correct as possible, thanks for updating it!

> I was getting compiler warnings on the UCRT64 toolchain because ntohl returns an unsigned long, where as PRIu32 resolves to a printf specifier for unsigned int. In practice this should not matter for Windows because long and int are the same size even on 64 bit Windows, but this is the ABI Microsoft decided on, and I have no idea why GCC is even warning for it.

Yes, I went again to check my toy example where I was testing this and I made a silly mistake. I now got the same warning you were getting and understand why too as you explained.

However, instead of `#ifdef` pre-processor directives, I would prefer to do a casting instead:
```cpp
fprintf(stream, "  Layer Vector ........... %" PRIu32 "\n", (uint32_t) ntohl(packet->root.vector));
```
How does that sound to you?

**Comment by braewoods** [comment]
Fine by me. It's been changed. I just felt like the macro one was better at explaining why the code was modified for future readers, due to the WIN32 macro check.

**Comment by hhromic** [comment]
> Fine by me. It's been changed. I just felt like the macro one was better at explaining why the code was modified for future readers, due to the WIN32 macro check.

Mmh yeah I think that you are right. The macro check was indeed better at explaining.
Apologies, can you revert it then to what you had before? I will approve and merge afterwards 👍.

**Comment by braewoods** [comment]
That should do it.

**Review by hhromic — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
